services:
  mongodb:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db
      - ./certs:/etc/ssl/mongo
    ports:
      - "27017:27017"
    networks:
      - caddy
    command: >
      mongod --bind_ip_all 
      --tlsMode requireTLS 
      --tlsCertificateKeyFile /etc/ssl/mongo/server.pem
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  mongodb_data:
    driver: local

networks:
  caddy:
    external: true