name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            
            # Define project and repo details
            WORKSPACE_DIR=~/workspace
            PROJECT_DIR=$WORKSPACE_DIR/mongo-template-db
            REPO_URL=https://github.com/DRAP-3312/mongo-template-db.git
            
            # Ensure workspace directory exists
            mkdir -p $WORKSPACE_DIR
            cd $WORKSPACE_DIR
            
            # Clone if project doesn't exist, or pull if it does
            if [ -d "$PROJECT_DIR/.git" ]; then
              echo "Repository exists, pulling latest changes."
              cd $PROJECT_DIR
              git pull
            else
              echo "Repository not found, cloning."
              rm -rf $PROJECT_DIR
              git clone $REPO_URL $PROJECT_DIR
              cd $PROJECT_DIR
            fi
            
            # Create .env file from secrets on the server
            cat << EOF > .env
            MONGO_ROOT_USERNAME=${{ secrets.MONGO_ROOT_USERNAME }}
            MONGO_ROOT_PASSWORD=${{ secrets.MONGO_ROOT_PASSWORD }}
            MONGO_DATABASE=${{ secrets.MONGO_DATABASE }}
            DOMAIN=${{ secrets.DOMAIN }}
            CADDY_EMAIL=${{ secrets.CADDY_EMAIL }}
            MONGO_EXPRESS_USERNAME=${{ secrets.MONGO_EXPRESS_USERNAME }}
            MONGO_EXPRESS_PASSWORD=${{ secrets.MONGO_EXPRESS_PASSWORD }}
            EOF
            
            # Load .env variables and deploy
            set -a
            source .env
            set +a
            docker stack deploy --compose-file .deploy/deploy-stack.yml mongodb --with-registry-auth
