name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            
            # Define project directory
            PROJECT_DIR=~/workspace/mongo-template-db
            DEPLOY_DIR=$PROJECT_DIR/.deploy
            
            # Create .env file from secrets on the server
            cat << EOF > $PROJECT_DIR/.env
            MONGO_ROOT_USERNAME=${{ secrets.MONGO_ROOT_USERNAME }}
            MONGO_ROOT_PASSWORD=${{ secrets.MONGO_ROOT_PASSWORD }}
            MONGO_DATABASE=${{ secrets.MONGO_DATABASE }}
            DOMAIN=${{ secrets.DOMAIN }}
            CADDY_EMAIL=${{ secrets.CADDY_EMAIL }}
            MONGO_EXPRESS_USERNAME=${{ secrets.MONGO_EXPRESS_USERNAME }}
            MONGO_EXPRESS_PASSWORD=${{ secrets.MONGO_EXPRESS_PASSWORD }}
            EOF
            
            # Navigate to the deploy directory
            cd $DEPLOY_DIR

            # Load .env variables and deploy
            set -a
            source $PROJECT_DIR/.env
            set +a
            docker stack deploy --compose-file deploy-stack.yml mongodb --with-registry-auth
